FROM nginx:1.23.3-alpine-slim
COPY ./dockerfiles/nginx/nginx.conf /etc/nginx/conf.d/custom.conf

# RUN apk add --update nodejs npm
# RUN npm i -g n && npm i -g pm2
# RUN n lts & PATH=$PATH

# WORKDIR /frontend
# COPY ./frontend .

# EXPOSE 5173

# RUN npm i 
# RUN npm run build
# CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
# RUN cd dist && mv * /usr/share/nginx/html/


